{% set name = "visitor" %}
{% set version = "0.1.3" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "2c737903b2b6864ebc6167eef7cf3b997126f1aa94bdf590f90f1436d23e480a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - visitor

about:
  home: https://github.com/mbr/visitor
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A tiny pythonic visitor implementation.'
  dev_url: https://github.com/mbr/visitor

extra:
  recipe-maintainers:
    - pmlandwehr
