# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TqbrViEtkeuZ3k3Z3Xqpyi3oY6PgIcPlG5D6Tw3IYIfx+zlWMqRvQ8RubBTM8xJdOvBU3nomS7EU7ST+g0jDMt0n6c5tUmMkZAWQOZGpKMW5xxrk2rs7tbrDUqfN2c/nC9LMnwM2Zso9tl+H/PmTr6mMc+g/WzjbkD5KuC0hZQPdDvL5tp8fzz0KZGnD2hCw5WlRYXvU+bgqz0b4j2S1ojcSXtUv2YKLJZU9l1tzB+LZgMNgwWqm8h4YPBODIKnRQW483rOaCthJCu2cf2bZm7dkAEtuWPxhVilzBIHLrlIMJyFlA+6ADD/0XtrNA88XEikihlGxqJ2uSYieXvQ0LoGcQgoRF4hJ6EwjbKbZVIhCucZSYluRKUzbAJwM82P+9+LEHMP5uZnFZEozTlHUyQrVHSxQZgtPu8G5CZF89s3N4TINs/Pd1fjjNstDTTOBbctxrx0gAdyBTBr6JPdBuQGUeA3ZPYi289SbAghKcnm4FUPMKlHbUwaDdI63pFDDSRDmoTxkBMs0psGBUmEQXpNjgKwD2xKowb9H8AG3+/s+Su0z6J72ERdiVwJRoK9U95SEeiGC+7/QU5Th8gGUp3R6RZ0O0OKu6OapikrpQoEtIq6zUBKvzbsWN3CYvAFqYI70H5rxh08CQRdT75mqYqXvE1b3gE1h0OPIZXX2G1s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
