travis:
  secure:
    BINSTAR_TOKEN: lLBAfjjFO8f3iWs3p7t/CKte3cKk+xE/6FV6rXlsortKTm6QeFpD+Rw0lF2RG0sq+cGZOogiq++28iWd8kz1GdM3qMFXM9KVxK2TGrzDmPCwoATyUPuUw+r/pjuYF5O/lUclmKWj8TVQCTDv+toPWAgd5+NLjL/JOLVqTJGsI6PkPhGBlUdDMLC+Av0PtxHxvnhqRrWmn/xQg0cuffmSztEThnnCDmTsMXKdMtGwAx4PeEU3p+YApEx1iv9Pb3Ae/5SHFd6o2IpygrXPRXSKA07rsgOtTEq9ItXL7GJLag7lBMt/cV/7/MFfMOtUmJ9b9P0WpVYXE9lhx6tL+kC46G7rqdLDOZxUKF24OooJrcEVC20ZXQnwusXGaz9ba/oV+LIFO7G2shOTDlprOGtt671HvJZEQV+xEXmVu9JVWiDRm+wPqUO2KfMQbGDQwGyH1mpiEJbnwbPAFZB4INLEUZk6de1/Exra4fHDq6FSQjprTfRevYyWFDfSSO0PgKRMzO2x577YyqvWbvJRpGkP3A7fxRhcUxkxmgt0H6/G8tXVDzZUD0Z0J7VYASFgOFEZeK9QBnUVibU9cL/4m0It0Ww693sdNcL9Jb8z4/jxiG023vSoLP+t4EF+tU9781sTlQaOdyuwwgoCPG6+n0qhMFQ4rPXM3OGqP0u+e18uMwM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
