travis:
  secure:
    BINSTAR_TOKEN: TqbrViEtkeuZ3k3Z3Xqpyi3oY6PgIcPlG5D6Tw3IYIfx+zlWMqRvQ8RubBTM8xJdOvBU3nomS7EU7ST+g0jDMt0n6c5tUmMkZAWQOZGpKMW5xxrk2rs7tbrDUqfN2c/nC9LMnwM2Zso9tl+H/PmTr6mMc+g/WzjbkD5KuC0hZQPdDvL5tp8fzz0KZGnD2hCw5WlRYXvU+bgqz0b4j2S1ojcSXtUv2YKLJZU9l1tzB+LZgMNgwWqm8h4YPBODIKnRQW483rOaCthJCu2cf2bZm7dkAEtuWPxhVilzBIHLrlIMJyFlA+6ADD/0XtrNA88XEikihlGxqJ2uSYieXvQ0LoGcQgoRF4hJ6EwjbKbZVIhCucZSYluRKUzbAJwM82P+9+LEHMP5uZnFZEozTlHUyQrVHSxQZgtPu8G5CZF89s3N4TINs/Pd1fjjNstDTTOBbctxrx0gAdyBTBr6JPdBuQGUeA3ZPYi289SbAghKcnm4FUPMKlHbUwaDdI63pFDDSRDmoTxkBMs0psGBUmEQXpNjgKwD2xKowb9H8AG3+/s+Su0z6J72ERdiVwJRoK9U95SEeiGC+7/QU5Th8gGUp3R6RZ0O0OKu6OapikrpQoEtIq6zUBKvzbsWN3CYvAFqYI70H5rxh08CQRdT75mqYqXvE1b3gE1h0OPIZXX2G1s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
