travis:
  secure:
    BINSTAR_TOKEN: PQqwSUszTRPzEf5mqWjdMAuXInb9aIfciFI5vhN3wquc+00dXQcL9rqU7b4ys2zWx30F5LHKCPt2xtGY9TyyaIaS3dd1kfrou7r0vH4d3mVE4Qh5Pf6wk5Cf0acik9HI25xEyD/fn+HTIsdiClGdxTkctUq+QR3FnYy8k7DXwjguKGkP3lMULO9ox+LYEQOvTi04Uztve1T5baFIosKwi/KXmIx4k2bZM3KfACDA5RUJGh/yFnvNvf1rUex17gxWhGtn48Dp41mf0o/c+zlV+XJgt9Zma8BF7u7k1UINtS7s1v725O0uZ1rHdMiuQGVR2cpsXbHOpOFaTFoJBRsSUbZsfoGOMYxXebKJPtdKFUW2WPQWWFhdsWHG/RT1c99mHsFXKARcTj09M0nyUpRf4mxXb9pBnGLv640n9VYDkQUTPewvia/d/YkHA6nkewx/aQ+vh9oIHUcqxGADWLQ8Sp3j5AtbgqIfozAZ4GOu3B0So5YxsIaKNeR6kigYe/tmT0JS2VBuAtnm9etYS31G/6fc8tYlUpJpTFGJsh608V/xTC1Ru4ybGOLqiGECVS0pNiOt2+VdM9BYrY87SwN0e5i758yTp8NDPVvvX0Y3bwI3AmAmH3nvk4pxX6C9bSggNrVspE2OlAwl2lFvVSG8EOhPmRtI6udTtHBP28sYLXM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
